### ISSUE TITLE
Import not working with explicit filter?

### ISSUE THREAD

**Issue by twMat** [inmysocks/TW5-TWederation#2]
(repost from irc because it it too easily lost there)

In attempting to import the contents of tiddler; 
http://twederation.tiddlyspot.com/#Communication 

into http://twed-notes.tiddlyspot.com/ 

I peek at the filter it uses for the tabs, i.e  [all[tiddlers+shadows]tag[Communication]] 

and I put this into my Fetch Tiddler Bundle filter and use the preset wiki: TWederation (which displays the correct url). But clicking Fetch Bundle doesn't result in anything... 
stays as missing link.

**Comment by inmysocks** [comment]
@twMat 
Oh, sorry. The bundle names now have a time stamp appended on the end so the link isn't to the correct tiddler. I will update that soon. Hopefully tomorrow morning. time for bed now.

**Comment by twMat** [comment]
Thanks. Looking forward to it :-)

**Comment by inmysocks** [comment]
This should be working now.
